.\" Copyright (c) 1985 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)ping.8	6.2 (Berkeley) 5/23/86
.\"
.TH PING 8 "May 12, 1993"
.UC 6
.SH NAME
ping \- send ICMP ECHO_REQUEST packets to network hosts
.SH SYNOPSIS
.B ping
[
.B \-CFILNORUdfjmnqruv
] [
.B \-c
.I count
] [
.B \-g
|
.B \-G
.I gateway
...
] [
.B \-t
.I timeout
] [
.B \-l
.I preload
] [
.B \-o
.I type
] [
.B \-p
.I pattern
] [
.B \-s
.I length
] [
.B \-T
.I ttl
] [
.B \-S
.I tos
]
.I host
.I default_multicast_interface
.SH DESCRIPTION
The DARPA Internet is a large and complex aggregation of
network hardware, connected together by gateways.
Tracking a single-point hardware or software failure
can often be difficult.
.I Ping
utilizes the
ICMP protocol's mandatory ECHO_REQUEST datagram to elicit an
ICMP ECHO_RESPONSE from a host or gateway.
ECHO_REQUEST datagrams (``pings'') have an IP and ICMP header,
followed by a \fBstruct timeval\fR, and then an arbitrary number
of ``pad'' bytes used to fill out the packet.
Default datagram length is 64 bytes, but this may be changed
using the command-line option.
.PP
The default mode is to send a packet every
.I timeout
seconds and display the response, including sequence number and
round-trip time if the packet size allows.  Two other modes are
available and are mutually exclusive:
.TP
.B \-C
Use cisco style packet sending; that is, spew packets as fast as
possible, but don't send packet N+1 until an reply or timeout has been
registered for packet N.  A '!' is printed for every response received
and a '.' is printed when a packet is not received during the
.I timeout
period.
Also, a '*' is printed whenever a duplicate response is received.
.TP
.B \-F
Floodping style packet sending; send packets as fast as possible,
attempting to send at at least 100 packets per second.  A '.' is printed
for every response that is missed and a '*' is printed whenever a
duplicate packet is received.  Only users in group zero (0) are allowd
to use this option.
.TP
.B \-G
Specify strict source routing via this gateway.  Multiple
gateways may be specified by repeating the option.  This option only
works on BSD 4.3 based systems that allow setting of IP options.
.TP
.B \-I
On systems where setting the TTL of outbound ICMP packets is supported,
this option sets the initial TTL to 1 and increments it each time an
ECHO_REQUEST packet is sent, until an ECHO_REPLY is received or the
TTL wraps to zero.
.TP
.B \-L
On systems supporting IP multicasting, disable multicast loopback.
.TP
.B \-N
Always lookup the returned IP addresses.  By default the IP source
address of packets received is printed in numeric form.  Use of this
option can adversely affect the round trip statistics.
.TP
.B \-O
Print Options.  The contents of the IP Options on packets sent and
received are listed.
.TP
.B \-R
Insert "record route" IP option in outgoing packets, summarizing
routes taken when program exits.  This option only works on BSD 4.3
based systems that allow setting of IP options.
.TP
.B \-S
.I tos
On systems where setting the TOS of outbound ICMP packets is supported,
this option sets the TOS field of all outbound ICMP ECHO_REQUEST
packets.
.TP
.B \-T
.I ttl
On systems where setting the TTL of outbound ICMP packets is supported,
this option sets the initial TTL of all outbound ICMP ECHO_REQUEST
packets.
.TP
.B \-U
Print round trip times and accumulate statistics with millisecond precision.
.TP
.B \-c
.I count
Terminate after
.I count
packets have been received.
.TP
.B \-d
Enable socket level debugging with the SO_DEBUG option.
.TP
.B \-f
Fast ping, send a packet as soon as a response is received.
.TP
.B \-g
Specify loose source routing via this gateway.  Multiple
gateways may be specified by repeating the option.  This option only
works on BSD 4.3 based systems that allow setting of IP options.
.TP
.B \-j
When the destination host is really an IP multicast group on systems
supporting IP multicasting, join the specified group.
.TP
.B \-l
Specifies the number of packets to
.I preload;
packets which are sent at startup before listening for a response.  The
deault is not to send any preload packets.
.TP
.B \-m
Enable printing of a summary of missed responses.
.TP
.B \-n
Disable hostname lookup of the returned IP addresses.  By default the
hostname and IP address of the destination host is displayed in the
header, summry and "record route" summary.  If the hostname lookup
fails, just the IP address is displayed.
.TP
.B \-o
Specifies the
.I type
of ICMP packet to send.
The default is an ECHO_REQUEST.  
The type may be abreviated down to one character.
Supported types are:
.RS 10
.TP
.B echo
Send an ECHO_REQUEST, expect and ECHO_RESPONSE.  
If at least eight bytes of data are available, round trip timing is done.
This is the default.
.TP
.B info
Send an INFO_REQUEST, expect and INFO_RESPONSE.
Round trip timing and additional data are not possible with this type.
.TP
.B mask
Send a MASK_REQUEST, expect a MASK_REPLY.
Round trip timing and additional data are not possible with this type.
.TP
.B router
Send a ROUTER_SOLICITATION, expect a ROUTER_ADVERTISEMENT.
Round trip timing and additional data are not possible with this type.
.TP
.B timestamp
Send a TIMESTAMP_REQUEST, expect a TIMESTAMP_REPLY.
Route trip and additional timing is always done.  Additional data may
be carried.
.RE
.TP
.B \-p
Specifies the
.I pattern
to fill unused data in the packets.  The default is to fill with the
data position modulo 256.  A
.I pattern
Is a string of hex digit pairs used to specify the contents of the bytes
of the packet.
Multiple patterns are concatenated.
The pattern(s) are replicated until they fill the packet.
.TP
.B \-q
Disable displaying of ping response messages, only display the summary.
.TP
.B \-r
Bypass the normal routing tables and send directly to a host on an attached
network.
If the host is not on a directly-attached network,
an error is returned.
This option can be used to ping a local host through an interface
that has no route through it (e.g., after the interface was dropped by
.IR routed (8C)).
.TP
.B \-t
Specify the
.I timeout
between pings in normal and cisco style modes as a floating point
number.  The default is one second.  Only users in group zero (0) are
allowed to specify a value less than one second.
.TP
.B \-u
Print round trip times and accumulate statistics with microsecond precision.
.TP
.B \-v
Verbose output.  ICMP packets other than ECHO_RESPONSE that are received
are listed.
.PP
When using \fIping\fR for fault isolation,
it should first be run on the local
host, to verify that the local network interface is up and
running.
Then, hosts and gateways further and further away
should be ``pinged''.
\fIPing\fR sends one datagram per second, and
prints one line of output for every ECHO_RESPONSE returned.
No output is produced if there is no response.
If an optional
.I length
is specified, it is used as the length of the data portion of the ICMP
ECHO_REQUEST packet.  The default
.I length
is 56 data bytes.
If an optional
.I count
is given, only that number of requests is sent.
Round-trip times and packet loss statistics are computed.
When all responses have been received or the program times out (with a
.I count
specified),
or if the program is terminated with a SIGINT, a brief
summary is displayed.
.PP
This program is intended for use in network testing, measurement
and management.
It should be used primarily for manual fault isolation.
Because of the load it could impose on the network,
it is unwise to use
.I ping
during normal operations or from automated scripts.
.SH AUTHOR
Mike Muuss
.SH CO-CONSPIRATORS
Ron Natalie, David Paul Zimmerman, Jeffrey C Honig, Vernon Schryver,
Dennis Ferguson.
.SH BUGS
More options than ls(1).
.SH SEE ALSO
netstat(1),
ifconfig(8C)
